version: "3.8"
services:
  agenda-db:
    image: postgres:15
    environment:
      POSTGRES_DB: agenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - agenda-db-data:/var/lib/postgresql/data

  agenda-service:
    build: ./agenda-service
    environment:
      - DATABASE_URL=postgres://postgres:postgres@agenda-db:5432/agenda
    ports:
      - "3002:3002"
    depends_on:
      - agenda-db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - agenda-service
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

volumes:
  agenda-db-data: